### ISSUE TITLE
List of removed stop words

### ISSUE THREAD

**Issue by shirish93** [LuminosoInsight/conceptnet-numberbatch#31]
Section 3.1 of the paper (second para) says some stop words were removed while pre-processing. Would there be a list of the words that were removed? Some very common stop words appear to be around, so just wanted to be sure which ones had been knowingly gotten rid of.

**Comment by rspeer** [comment]
The only stopwords removed were "the", "a", and "an" (when they are not the only word), and "to" (when it's the first word).

See https://github.com/commonsense/conceptnet5/blob/master/conceptnet5/language/english.py for the actual code.
